### ISSUE TITLE
Index was outside the bounds of the array in ArmoredInputStream.Decode

### ISSUE THREAD

**Issue by chriswhisenhunt** [mattosaurus/PgpCore#153]
I love easy to use PgpCore is but I'm finding that when I encode a file using a public key from a vendor I get the following error.

Index was outside the bounds of the array. 

Here's the stack 

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Org.BouncyCastle.Bcpg.ArmoredInputStream.Decode(Int32 in0, Int32 in1, Int32 in2, Int32 in3, Int32[] result)
   at Org.BouncyCastle.Bcpg.ArmoredInputStream.DoReadByte()
   at Org.BouncyCastle.Bcpg.ArmoredInputStream.ReadByte()
   at Org.BouncyCastle.Bcpg.BcpgInputStream.NextPacketTag()
   at Org.BouncyCastle.Bcpg.OpenPgp.PgpKeyRing.ReadOptionalTrustPacket(BcpgInputStream bcpgInput)
   at Org.BouncyCastle.Bcpg.OpenPgp.PgpPublicKeyRing..ctor(Stream inputStream)
   at Org.BouncyCastle.Bcpg.OpenPgp.PgpObjectFactory.NextPgpObject()
   at Org.BouncyCastle.Bcpg.OpenPgp.PgpObjectFactory.AllPgpObjects()
   at PgpCore.Utilities.ReadPublicKey(Stream publicKeyStream)
   at PgpCore.EncryptionKeys.<>c__DisplayClass24_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at PgpCore.PGP.EncryptStream(Stream inputStream, Stream outputStream, Boolean armor, Boolean withIntegrityCheck, String name)
   at PgpCore.PGP.EncryptFile(String inputFilePath, String outputFilePath, Boolean armor, Boolean withIntegrityCheck, String name)

Any thoughts as a path for troubleshooting?

Thanks!

**Comment by mattosaurus** [comment]
Hi, I'm not sure what could be causing this from the error though it may be that the public key is invalid. Are you able to encrypt files using this key in other applications like the gpg command line app?

If so are you able to share your code and if possible a key that reproduces this error.
