### ISSUE TITLE
PGPCore version 5.6.0 Encryption Issue

### ISSUE THREAD

**Issue by WeidongShen** [mattosaurus/PgpCore#162]
PGPCore version 5.6.0 throws the following exception:

System.ArgumentException: No encryption keys in keyring
   at PgpCore.Utilities.FindBestEncryptionKey(PgpPublicKeyRing publicKeys)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PgpCore.EncryptionKeys.<>c__DisplayClass41_0.<InitializeKeys>b__2()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at PgpCore.EncryptionKeys.get_EncryptKeys()
   at PgpCore.PGP.EncryptStreamAsync(Stream inputStream, Stream outputStream, Boolean armor, Boolean withIntegrityCheck, String name)
   at PgpCore.PGP.EncryptStreamAsync(Stream inputStream, Stream outputStream, Stream publicKeyStream, Boolean armor, Boolean withIntegrityCheck, String name)

when I call the following method:

await pgp.EncryptStreamAsync(inputStream, outputStream, publicKeyStream);

The PGP public key used is as follows:

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGiBEg3CMERBADw9yM1g7Yr8/pfTu6m5gtsJHNHOinEbVFCARbOKbmMCIthxFi8
xCEQLhoL4CKW5xL4MzJQq2F08zZCjR580y71y6lPThZIc3iIz21vFy0t7OZ/Q9ue
bjTt8YqaHOOOdPg1ZQVysgjLjuEaS1rPaBczI/RbgpHvkkGPxRYtcH8yiwCg/3IF
K5MJ8ypa//wH1HlDHylMXRMD/1PAqMK3+2stxiivbok3fmRtSR6P/Vj8BRd/Qda4
RilN6MBpfbK7YKas1DruusAamkcM89o9bIi5Nc5xceD8L0dHcI6+gdYcvGvmrLuX
7e59pMdPH/g0RJp31W7m9u3cHSSDeZ0Ft67Btwe00vtiF+NdIECttRadREsgu67/
mxrcA/9UAC8y9yA6i6yjjUhh3yTXvMUpqzeFgvA8Q7JynzbHXwYowzNWkp1qviVE
krbHrHBBgp3UCe1kjZxPaiOFUKhuBsK8bVl9XF5B0ZRwHSpjgh9prq3po2aSGoEV
l1ngI0LnUXkx/78OOUlpFfvj8opsaI7u7BRjWX24Rzvi4nj/R7QtcGF5cm9sbCA8
UGF5cm9sbEludGVncmF0aW9uQGJlbmVmaXRmb2N1cy5jb20+iQBOBBARAgAOBQJI
NwjBBAsDAgECGQEACgkQuHDD/nUKpfyJqACfbAQ1W1rZwp08be8wpRuNElggjfkA
njZ9OSlafn5Zx67Z5eJ3IdVmwOrruQINBEg3CMEQCAD2Qle3CH8IF3KiutapQvMF
6PlTETlPtvFuuUs4INoBp1ajFOmPQFXz0AfGy0OplK33TGSGSfgMg71l6RfUodNQ
+PVZX9x2Uk89PY3bzpnhV5JZzf24rnRPxfx2vIPFRzBhznzJZv8V+bv9kV7HAarT
W56NoKVyOtQa8L9GAFgr5fSI/VhOSdvNILSd5JEHNmszbDgNRR0PfIizHHxbLY72
88kjwEPwpVsYjY67VYy4XTjTNP18F1dDox0YbN4zISy1Kv884bEpQBgRjXyEpwpy
1obEAxnIByl6ypUM2Zafq9AKUJsCRtMIPWakXUGfnHy9iUsiGSa6q6Jew1XpMgs7
AAICCACsNY1e265A0kIrn90toS7bwMjOounN79QT3zlsiUk2P1cN5CVWz7dAO8UI
UfdJSHk1Gps9eCKCKcFp8xZA7TQAdLirq/0S4t4wDqxSbVHRj4PWYiGuoDBKGGa3
RjlpcCtwvQoNEx66S1OuvmVhVExjiQM9Weyo5Q6U1yYjh9pFR4GWvVrP0pWbIDoU
0hXJOlDWEEdMCZ0JpzZ1nXpLcvGUAvcIVB/LjmqPFsJjvpbnf6xWO9ruHUROeOuy
+Jl6kbD5PV2dy/s8K2lw4yVXgXa26vsSAxz294LeoAXGGXqhOS9ibY/gsLrYHER3
x7IG6oA4zpsP+1TZ5UdfTZXLHkNJiQBGBBgRAgAGBQJINwjBAAoJELhww/51CqX8
dKkAoKcfdiIlPGwapd66e+021NMy5nCnAKCLgj3pSWN3hEL4v/oWnFYS1dyYJQ==
=ckbw
-----END PGP PUBLIC KEY BLOCK-----

This problem does not exist in PGPCore version 5.5.0.

**Comment by mattosaurus** [comment]
This is probably due to the changes made in v5.6.0 to do with selecting the correct key if multiple are available. I'll have a look into it.

**Comment by mattosaurus** [comment]
This should hopefully be fixed in v5.7.0 that I've just published.

**Comment by WeidongShen** [comment]
Thanks!
