### ISSUE TITLE
Could not find any signing keys in keyring

### ISSUE THREAD

**Issue by Phoenix01001010** [mattosaurus/PgpCore#289]
Hello, I have used the Pgpcore 6.3.1 library in my project to sign and encrypt a string. The code works fine locally, but when deployed as a web app on Azure, I am encountering an error: "Could not find any signing keys in the keyring." I have been reading the keys from the appsettings file for now and passing them as a string (I also tried using a memory stream), but none of these methods are working. Could someone please help me identify the possible root cause?

string? publicKey = Helper.GetAppSettings("KeyConfig:PublicKey");
string? privateKey = Helper.GetAppSettings("KeyConfig:PrivateKey");
EncryptionKeys signingKey = new(publicKey, privateKey, passphrase); -Error line

**Comment by mattosaurus** [comment]
Hi, the issue is likely because the path to your appsettings file will be different on your local machine than in Azure so you won't be loading any values in Azure.

I'd suggest using the inbuilt [configuration provider](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-8.0) rather than a custom helper class and making it available via DI.

```
        public static IConfiguration Configuration { get; } = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
            .AddEnvironmentVariables()
            .Build();
```

**Comment by Phoenix01001010** [comment]
Hello @mattosaurus Thank you for your speedy response. I can confirm that it's not an issue with values not being loaded in Azure. With additional logging, I could confirm this.

Full stack trace:

Error:  Encryption failed. [Could not find any signing keys in keyring    at PgpCore.Utilities.FindBestSigningKey(PgpSecretKeyRingBundle secretKeyRingBundle)
   at PgpCore.EncryptionKeys.<>c__DisplayClass48_0.<InitializeKeys>b__8()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at PgpCore.EncryptionKeys.get_SigningSecretKey()
   at PgpCore.EncryptionKeys.InitializeKeys(IEnumerable`1 publicKeyRings)
   at PgpCore.EncryptionKeys..ctor(String publicKey, String privateKey, String passPhrase)

**Comment by ustaalon** [comment]
@mattosaurus 
The same issue happens to me as well. Using the same code from the examples. When downgrading to previous version its working fine (5.2.0 - the version I used before upgrading to 6.5.1).

**Comment by mattosaurus** [comment]
Hi, @ustaalon / @Phoenix01001010. Do you have an example project that you can share with me that I can use to investigate further?

**Comment by Pd-26** [comment]
Hi @mattosaurus  I am also facing the same issue. Any update on this ? I am passing Publickeystream and private keystream from azure keyvault.
`  public PGPEncryptionKeys2(Stream publicKeyStream, Stream privateKeyStream, string passPhrase)
  {
      if (publicKeyStream == null)
          throw new ArgumentException("PublicKeyStream");
      if (privateKeyStream == null)
          throw new ArgumentException("PrivateKeyStream");
      if (passPhrase == null)
          throw new ArgumentNullException(nameof(passPhrase), "Invalid Pass Phrase.");

      var keyRings = Utilities.ReadAllKeyRings(publicKeyStream);

      _secretKeys = new Lazy<PgpSecretKeyRingBundle>(() => Utilities.ReadSecretKeyRingBundle(privateKeyStream));
      _passPhrase = passPhrase;
      InitializeKeys(keyRings);
  }`

**Comment by mattosaurus** [comment]
Hi, I've created a basic example here and all works as expected, both locally and when deployed to Azure.

https://github.com/mattosaurus/PgpCore.Api

If someon's able to share a project with me that replicates this issue then I'll take another look.

**Comment by ustaalon** [comment]
Hey @mattosaurus sorry for not sharing any more details. I will try to do something over this weekend or the next one. I will try to make simple project to reproduce it, as I can't share the original code.

**Comment by mattosaurus** [comment]
Hi @ustaalon, no worries. Does the above example help you out or can you fork that to demonstrate?

**Comment by LarsBauer** [comment]
I have my public key, private key and passphrase stored as secrets in Azure Key Vault and linked as Key Vault Reference to my Azure Function App. I received the same error when uploading the key values via Azure Portal. It cost me half a day to figure out that line breaks inside the key files seem to be important. That formatting is getting lost when copy pasting the values in the portal. So I switched to Azure CLI to upload my key contents to the Key Vault and after that it works just fine. Not sure if its related to the issues you guys are facing but just wanted to give you this hint.
```bash
az keyvault secret set --name PgpPublicKey --vault-name <mykeyvault> --file .\<mykey>_public.asc
az keyvault secret set --name PgpPrivateKey --vault-name <mykeyvault> --file .\<mykey>_private.asc
```

**Comment by peterasamoah7** [comment]
Experiencing this as well after deploying to Azure Container Job. Works fine locally. Seeing the same error as mentioned above. Downgrading to version 5.2.0 resolves this issue. Seems something changed between version which is affecting this.

**Comment by mattosaurus** [comment]
Hi @peterasamoah7, are you able to provide an example project that can demonstrate this? I've provided a working solution above if the code there is of any help to you.

**Comment by mattosaurus** [comment]
Hi @ragnarredbeerd, thanks for creating a demo repo. Looks like it's currently private so could you please either make it public or grant me access.

I think I'd missed the part about keys coming from key vault sot hat should help me investigate as well.

**Comment by dbockspp** [comment]
I am having the same problem when trying to use code in Azure that works locally on my dev machine.  Locally I just put the private key string (include newlines, etc) along with the passPhrase into config settings in local secrets.json.  

I tried to add the same settings in my Azure App Service app settings.  The app service finds the settings (or I would log an error about not getting them) but I cannot decrypt.

"Could not find any signing keys in keyring"

Does something else PGP-related need to be set up in Azure like I would have on my local machine where I generated the public and private keys?

**Comment by mattosaurus** [comment]
@dbockspp if you're loading from a local file then my example above should be able to help you as this works in Azure.

https://github.com/mattosaurus/PgpCore.Api

**Comment by peterasamoah7** [comment]
Hello, so I got this working in Azure.

In my case as I already described above, my private key and public key are both stored as base64 strings in key vault and my passphrase is a string literal.

When I pull the keys from Azure Key Vault, I convert the base64 strings into streams and use the EncryptionKeys constructor that take public and private key as streams and passphrase as a string.

This fixed the issue described in my original post. I'm not sure why but this solved my headache. Hope this helps.
________________________________
