### ISSUE TITLE
 How to decrypt in web api?

### ISSUE THREAD

**Issue by Amber-Wish** [mattosaurus/PgpCore#87]
Hello, sir!I use HttpContext.Request.Body to call DecryptStreamAsync method, and then it has an error:"Object reference not set to an instance of an object".The following information is error tracking information：
at PgpCore.PGP.<DecryptAsync>d__78.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PgpCore.PGP.<DecryptStreamAsync>d__76.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by Amber-Wish** [comment]
I use postman to test my api.
![image](https://user-images.githubusercontent.com/55867470/91249370-51f88a00-e789-11ea-867a-1b4038b7ad05.png)

**Comment by mattosaurus** [comment]
Hi, if you want to share your code I'll have a look over it when I return from holiday next week.

My guess is that you are not reading your request body to the end before you try and decrypt it so you are returning an incomplete result.

**Comment by Amber-Wish** [comment]
Sorry sir, it took so long to reply. I found that I couldn't use postman to initiate a request to decrypt the encrypted content, so I created a new client program to encrypt, and the encrypted content was base64-encoded and then requested the decryption interface through http. It succeeded. I am not sure if my method is correct.
